# Generated by Django 2.0.5 on 2018-06-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('side_effects', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('previous', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compound1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compound2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compound3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('compound4', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('charges', models.DecimalField(decimal_places=0, max_digits=5)),
                ('notes', models.TextField()),
            ],
        ),
    ]
