# Generated by Django 2.0.5 on 2018-06-25 03:23

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mode_of_delivery', models.CharField(blank=True, choices=[('1', 'Vaginal Delivery'), ('2', 'Breech Delivery'), ('3', 'Vaccum Delivery'), ('4', 'Forceps Delivery'), ('5', 'Cesarian')], max_length=1, null=True)),
                ('indication', models.CharField(blank=True, max_length=64, null=True)),
                ('nicu_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('surfuctant', models.CharField(blank=True, max_length=16, null=True)),
                ('inv_vent_type', models.CharField(blank=True, max_length=16, null=True)),
                ('inv_vent_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('non_inv_vent_type', models.CharField(blank=True, max_length=16, null=True)),
                ('non_inv_vent_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tpn_type', models.CharField(blank=True, max_length=16, null=True)),
                ('start_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tpn_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('culture', models.BooleanField(default=True)),
                ('bacteria', models.CharField(blank=True, max_length=32, null=True)),
                ('antibiotics', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('phototherapy_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('onset_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('congenital_malformations', models.TextField(blank=True, null=True)),
                ('congenital_disease', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=16)),
                ('batch', models.CharField(max_length=16)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('expiry', models.DateField()),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masters.Vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('sur_name', models.CharField(blank=True, max_length=32)),
                ('status', models.BooleanField(default=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('G', 'Gender'), ('M', 'Male'), ('F', 'Female')], default='G', max_length=1)),
                ('blood', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-'), ('7', 'AB+'), ('8', 'AB-'), ('9', 'Blood Group')], default='9', max_length=1)),
                ('registration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=32, null=True)),
                ('father_blood', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-'), ('7', 'AB+'), ('8', 'AB-'), ('9', 'Blood Group')], default='9', max_length=1)),
                ('father_occupation', models.CharField(blank=True, max_length=32, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_blood', models.CharField(choices=[('1', 'A+'), ('2', 'A-'), ('3', 'B+'), ('4', 'B-'), ('5', 'O+'), ('6', 'O-'), ('7', 'AB+'), ('8', 'AB-'), ('9', 'Blood Group')], default='9', max_length=1)),
                ('mother_occupation', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('pob', models.CharField(blank=True, max_length=32, null=True)),
                ('delivery_doctor', models.CharField(blank=True, max_length=32, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('birth_height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('birth_headcm', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('last_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('last_height', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4)),
                ('last_headcm', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4)),
                ('last_date', models.DateTimeField(auto_now=True, null=True)),
                ('last_note', models.CharField(blank=True, max_length=256, null=True)),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('vac_scheduled_date', models.DateField(blank=True, null=True)),
                ('vac_actual_date', models.DateField(auto_now_add=True, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.Inventory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.Patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='masters.Vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True)),
                ('headcm', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True)),
                ('bp_systolic', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('bp_diastolic', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('signs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('symptoms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('diagnosis', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('investigations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('treatment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('vaccination', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('next_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patients.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='birthhistory',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
    ]
