# Generated by Django 2.0.5 on 2018-05-07 18:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_number', models.PositiveSmallIntegerField(default=0)),
                ('first_name', models.CharField(default='', max_length=32)),
                ('sur_name', models.CharField(blank=True, max_length=32)),
                ('status', models.BooleanField(default=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('G', 'Gender'), ('M', 'Male'), ('F', 'Female')], default='G', max_length=1, null=True)),
                ('blood', models.CharField(blank=True, max_length=3, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=32, null=True)),
                ('father_blood', models.CharField(blank=True, max_length=3, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=32, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_blood', models.CharField(blank=True, max_length=3, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=32, null=True)),
                ('mother_phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('pob', models.CharField(blank=True, max_length=32, null=True)),
                ('delivery_doctor', models.CharField(blank=True, max_length=32, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('birth_height', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('birth_headcm', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True)),
                ('last_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('last_height', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True)),
                ('last_headcm', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True)),
                ('last_date', models.DateTimeField(auto_now=True, null=True)),
                ('last_note', models.CharField(blank=True, max_length=256, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
