# Generated by Django 2.0.5 on 2018-05-08 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestation', models.PositiveSmallIntegerField()),
                ('mode_of_delivery', models.CharField(blank=True, choices=[('1', 'Vaginal Delivery'), ('2', 'Breech Delivery'), ('3', 'Vaccum Delivery'), ('4', 'Forceps Delivery'), ('5', 'Cesarian')], max_length=1, null=True)),
                ('indication', models.CharField(blank=True, max_length=64, null=True)),
                ('nicu_duration', models.PositiveSmallIntegerField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('surfuctant', models.CharField(blank=True, max_length=16, null=True)),
                ('inv_vent_type', models.CharField(blank=True, max_length=16, null=True)),
                ('inv_vent_duration', models.PositiveSmallIntegerField()),
                ('non_inv_vent_type', models.CharField(blank=True, max_length=16, null=True)),
                ('non_inv_vent_duration', models.PositiveSmallIntegerField()),
                ('tpn_type', models.CharField(blank=True, max_length=16, null=True)),
                ('start_day', models.PositiveSmallIntegerField()),
                ('tpn_duration', models.PositiveSmallIntegerField()),
                ('culture', models.BooleanField(default=True)),
                ('bacteria', models.CharField(blank=True, max_length=32, null=True)),
                ('antibiotics', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('phototherapy_day', models.PositiveSmallIntegerField()),
                ('onset_day', models.PositiveSmallIntegerField()),
                ('congenital_malformations', models.TextField(blank=True, null=True)),
                ('congenital_disease', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='birthhistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
    ]
